name: Docker CI/CD

on:
  push:
    branches:
      - release/prod  # Trigger on push to the main branch
  pull_request:
    branches:
      - release/prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub (or another container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub-username/your-app:${{ github.sha }} .

      # Push the Docker image
      - name: Push Docker Image
        run: |
          docker push your-dockerhub-username/your-app:${{ github.sha }}

      # Optional: Deploy to server using SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull your-dockerhub-username/your-app:${{ github.sha }}
            docker stop your-app || true
            docker run -d -p 80:8000 --name your-app your-dockerhub-username/your-app:${{ github.sha }}